In [ ]:
import tensorflow as tf
print('Tensorflow version:',tf.__version__)

Tensorflow version: 2.15.0


In [ ]:
mnist=tf.keras.datasets.mnist
(x_train, y_train), (x_test,y_test)=mnist.load_data()
x_train, x_test=x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [ ]:
predictions=model(x_train[:1]).numpy()
predictions

array([[ 0.41858494,  0.25720343, -0.5254493 ,  0.03687009, -0.85723966,
        -0.24640554,  0.06700036,  0.42341855, -0.32271424, -0.28763407]],
      dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.15638171, 0.13307573, 0.06084111, 0.10676017, 0.04366187,
        0.08042373, 0.11002584, 0.15713942, 0.07451501, 0.0771754 ]],
      dtype=float32)

In [ ]:
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
loss_fn(y_train[:1],predictions).numpy()

2.5204458

In [ ]:
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])

In [ ]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 12s 6ms/step - loss: 0.2949 - accuracy: 0.9140
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1426 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 10s 6ms/step - loss: 0.1064 - accuracy: 0.9677
Epoch 4/5
1875/1875 [==============================] - 14s 7ms/step - loss: 0.0870 - accuracy: 0.9737
Epoch 5/5
1875/1875 [==============================] - 11s 6ms/step - loss: 0.0735 - accuracy: 0.9768


In [ ]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0753 - accuracy: 0.9769 - 762ms/epoch - 2ms/step


[0.07532088458538055, 0.9768999814987183]

In [ ]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.6147878e-08, 2.2776810e-08, 7.3042224e-06, 6.8858557e-05,
        3.8391800e-11, 2.8469483e-07, 6.4447783e-14, 9.9991596e-01,
        2.3335291e-07, 7.1034024e-06],
       [1.1356150e-07, 2.4245211e-04, 9.9793810e-01, 8.0200110e-04,
        5.2849283e-12, 1.4035966e-05, 3.8720241e-06, 2.0576612e-09,
        9.9923462e-04, 9.5337158e-12],
       [2.2379663e-07, 9.9923694e-01, 2.4718945e-04, 1.7885368e-05,
        1.3090696e-05, 1.8275166e-06, 2.6255466e-05, 1.4300786e-04,
        3.1102233e-04, 2.6685402e-06],
       [9.9992633e-01, 3.3181884e-09, 2.3551978e-05, 3.3500839e-07,
        1.1186691e-07, 2.4693268e-06, 9.0338517e-06, 2.6997222e-05,
        5.5199045e-09, 1.1239563e-05],
       [1.1594282e-05, 1.1566461e-09, 6.6667440e-07, 3.3362355e-09,
        9.9544263e-01, 4.6271848e-07, 1.0658859e-05, 3.0215841e-05,
        1.4360155e-07, 4.5035388e-03]], dtype=float32)>