In [2]:
import tensorflow as tf
print('tensorflow version:',tf.__version__)

tensorflow version: 2.15.0


# Load Dataset

In [3]:
mnist=tf.keras.datasets.mnist
(x_train,y_train), (x_test,y_test)=mnist.load_data()
x_train,x_test=x_train/255.0,x_test/255.0

11490434/11490434 [==============================] - 0s 0us/step


# Build a machine learning model

In [5]:
model=tf.keras.models.Sequential([tf.keras.layers.Flatten(input_shape=(28,28)),
                                  tf.keras.layers.Dense(128,activation='relu'),
                                  tf.keras.layers.Dropout(0.2),
                                  tf.keras.layers.Dense(10)])

In [6]:
predictions=model(x_train[:1]).numpy()
predictions

array([[-0.06795362, -0.00364936,  0.36043853, -0.09182775, -1.1782353 ,
         0.08942837, -0.76208085,  0.19559622,  0.25114468,  0.31481   ]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.09327669, 0.09947184, 0.14315993, 0.09107617, 0.03073151,
        0.10917501, 0.04659266, 0.12140354, 0.12833814, 0.13677454]],
      dtype=float32)

In [9]:
loss_fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [11]:
loss_fn(y_train[:1],predictions).numpy()

2.2148032

In [12]:
model.compile(optimizer='adam',loss=loss_fn,metrics=['accuracy'])

In [13]:
model.fit(x_train,y_train,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 3ms/step - loss: 0.2944 - accuracy: 0.9145
Epoch 2/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.1396 - accuracy: 0.9581
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1061 - accuracy: 0.9684
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0866 - accuracy: 0.9736
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0734 - accuracy: 0.9766


In [14]:
model.evaluate(x_test,y_test,verbose=2)

313/313 - 1s - loss: 0.0742 - accuracy: 0.9757 - 561ms/epoch - 2ms/step


[0.07419728487730026, 0.9757000207901001]

In [15]:
probability_model=tf.keras.Sequential([model,tf.keras.layers.Softmax()])

In [16]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[5.79090909e-07, 2.24752039e-09, 3.11803815e-05, 4.11470792e-05,
        1.89439393e-12, 1.94428139e-06, 1.03362204e-13, 9.99922276e-01,
        9.35619710e-07, 2.08980441e-06],
       [9.10447273e-10, 1.84803415e-04, 9.99811351e-01, 3.61488424e-06,
        7.83271865e-15, 2.17961862e-08, 1.23533042e-07, 2.50874659e-14,
        1.29818687e-07, 1.57233693e-14],
       [5.08998437e-06, 9.98696625e-01, 1.83705051e-04, 7.68008522e-06,
        1.30718501e-04, 3.26906593e-05, 5.71715827e-05, 3.25744099e-04,
        5.60193148e-04, 3.52532368e-07],
       [9.99867678e-01, 2.39739284e-10, 9.69605899e-05, 4.01603089e-08,
        2.82128854e-09, 8.65556672e-07, 1.27928861e-05, 7.42107204e-07,
        8.32810599e-07, 2.00082050e-05],
       [3.70498310e-05, 8.21066048e-10, 2.18234272e-05, 9.20243970e-09,
        9.82641280e-01, 4.73428230e-07, 4.94012784e-06, 5.17449225e-04,
        7.19650245e-07, 1.67764481e-02]], dtype=float32)>